import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
export type UserRole = 'Admin' | 'Supervisor' | 'Employee'

const navigationConfig: NavigationTree[] = [
    {
        key: 'Salary_Calculator',
        path: '/salary-management',
        title: 'Home',
        translateKey: '',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Admin', 'Supervisor'],
        subMenu: [],
    },
    {
        key: 'singleMenuItem',
        path: '/user-management',
        title: "User Management",
        translateKey: '',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Admin', 'Supervisor'],
        subMenu: [],
    },
    {
        key: 'RequestManagement',
        path: '',
        title: 'Request Management',
        translateKey: '',
        icon: 'request',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['Admin', 'Supervisor'],
        subMenu: [
            {
                key: 'RequestManagement',
                path: '/request-management',
                title: "Request OT/Field Work",
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            },
            {
                key: 'RequestManagement.item22',
                path: '/request-dayoff-management',
                title: 'Request Day Off',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'SalaryManagement',
        path: '',
        title: 'Salary Management',
        translateKey: '',
        icon: 'moneysalary',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['Admin', 'Supervisor'],
        subMenu: [
            {
                key: 'SalaryManagement',
                path: '/salary-calculator',
                title: 'Salary Calculator',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            },
            {
                key: 'salary.report',
                path: '/salary-report',
                title: 'Salary Reports',
                translateKey: '',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'attendanceMenu',
        path: '/attendance',
        title: 'ຂໍ້ມູນການມາວຽກ',
        translateKey: '',
        icon: 'groupCollapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: ['Admin', 'Supervisor'],
        subMenu: [
            {
                key: 'attendance.records',
                path: '/attendance-records',
                title: 'ຂໍ້ມູນການມາວຽກ ແລະ ລາຍລະອຽດ',
                translateKey: 'nav.Attendance.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            },
            {
                key: 'otandfieldwork.records',
                path: '/otandfieldwork-records',
                title: 'ຂໍ້ມູນ OT ແລະ ວຽກນອກສະຖານທີ່',
                translateKey: 'nav.OTandFieldWork.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            },
            {
                key: 'dayoff.requests',
                path: '/dayoff-requests',
                title: 'ຂໍ້ມູນການຂໍລາພັກ',
                translateKey: 'nav.Attendance.item3',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['Admin', 'Supervisor'],
                subMenu: [],
            }
        ],
    },
    {
        key: 'user',
        path: '/user-profile',
        title: 'ໂປຣໄຟລ໌ພະນັກງານ',
        translateKey: '',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Employee'],
        subMenu: [],
    },
    {
        key: 'user.ot.fieldwork.requests',
        path: '/user-ot-fieldwork-requests',
        title: 'ຂ້ໍມູນ OT ແລະ ວຽກນອກສະຖານທີ່',
        translateKey: 'nav.UserProfile.item2',
        icon: 'groupCollapseMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Employee'],
        subMenu: [],
    },
    {
        key: 'user.dayoff.requests',
        path: '/user-dayoff-requests',
        title: 'ຂໍ້ມູນການຂໍລາພັກ',
        translateKey: 'nav.UserProfile.item2',
        icon: 'groupCollapseMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['Employee'],
        subMenu: [],
    },
]

export default navigationConfig
